#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""validate_xr_layer.py

Gate for the XR layer (addendum A1) and the provenance block of a Character Pack.
Standard library only, Python 3.8+.

What it does
  1. Validates the xr_layer and provenance blocks against schemas/xr-layer.addendum.schema.json
     with a small built-in JSON Schema engine (the schema file stays the single source of
     truth for structure).
  2. Runs semantic rules XRnnn (XR layer over a moving robot) and PVnnn (provenance of
     avatars generated by distributors). Limits come from policy/xr-gate-policy.v1.json.
  3. Applies waivers (reason, approver, expiry, creator cannot approve their own waiver).
  4. Writes a text report and, optionally, SARIF 2.1.0 with partial fingerprints and digests
     of the tool, schema, policy and input, so that a verdict can be reproduced.

Exit codes (same convention as the ScriptCheckup CLI)
  0  clean: no findings (waived findings do not count)
  1  warnings only: pass with a mark
  2  at least one unwaived error: block
  3  infrastructure failure (unreadable input, broken schema or policy, internal error):
     block. The gate is fail-closed: a crash is never reported as a pass.

The base pack structure is read by a few tolerant accessors below (base_state_items,
base_assets, base_surfaces): target_surfaces and assets[].asset_id as in the repository
pack, with fallbacks to surfaces and assets[].id. If your base schema names things
differently, change those accessors and nothing else.

Transition for packs written before A1. A pack with neither xr_layer nor provenance is a
legacy v1 pack. XR001 and PV001 are reported for it with the severity given by
policy.legacy_severity (warning by default), so existing packs pass with a mark. As soon as
a pack carries any A1 block, both rules are errors.
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import math
import os
import re
import sys
from pathlib import Path

TOOL_NAME = "character-pack-xr-gate"
TOOL_VERSION = "A1.0.0"
EXIT_CLEAN, EXIT_WARN, EXIT_ERROR, EXIT_INFRA = 0, 1, 2, 3

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SCHEMA = ROOT / "schemas" / "xr-layer.addendum.schema.json"
DEFAULT_POLICY = ROOT / "policy" / "xr-gate-policy.v1.json"


class InfraError(Exception):
    """Tool-level failure. Must block (fail-closed), never pass."""


# ---------------------------------------------------------------- rule catalogue

RULES = {
    "XR000": ("Base pack structure not recognized", "error"),
    "XR001": ("xr_glasses surface claimed without xr_layer", "error"),
    "XR002": ("Schema violation in xr_layer or provenance", "error"),
    "XR003": ("xr_layer.states does not match the pack states", "error"),
    "XR005": ("Tier asset reference or media kind invalid", "error"),
    "XR006": ("safe_state missing or not safe", "error"),
    "XR007": ("Precise tolerance needs marker registration and a stationary state", "error"),
    "XR008": ("Registration error budget versus tolerance class", "error"),
    "XR009": ("moving_fallback missing or invalid", "error"),
    "XR010": ("Tracking-loss policy out of bounds", "error"),
    "XR011": ("Safety limits exceeded (flash rate, e-stop response)", "error"),
    "XR012": ("Character bounds invalid or inside a keep-out volume", "error"),
    "XR013": ("AI disclosure labels missing", "error"),
    "XR014": ("Caption angular size below guideline", "warning"),
    "XR015": ("Audit retention above policy", "warning"),
    "XR020": ("Media descriptor violates policy", "error"),
    "XR021": ("XR media budget exceeded or unverifiable", "error"),
    "XR022": ("speaking_driver inconsistent with assets", "error"),
    "XR023": ("Field-of-view coverage above heuristic limit", "warning"),
    "XR024": ("Tier declared but no listed device class can show it", "warning"),
    "XR025": ("voice_lines arrays are not index-aligned across locales", "error"),
    "XR026": ("T2 glb asset differs from the v1 xr.bundle_asset of the state", "error"),
    "PV001": ("provenance block missing", "error"),
    "PV002": ("Asset not covered by provenance", "error"),
    "PV003": ("Platform terms evidence incomplete or stale", "error"),
    "PV004": ("original_design not backed by similarity screening", "error"),
    "PV005": ("Human review missing or negative", "error"),
    "PV006": ("Machine-readable AI marking missing", "error"),
    "PV007": ("Reference input without rights evidence", "error"),
    "PV008": ("Platform may train on prompts and references", "warning"),
    "PV009": ("Provenance timestamps inconsistent", "error"),
    "PV010": ("Unknown generation platform without a name", "error"),
    "PV011": ("No human authorship evidence", "warning"),
    "PV012": ("Generation job without prompt hash", "warning"),
    "WV001": ("Waiver rejected or stale", "warning"),
}

SEVERITIES = ("error", "warning", "note")


# ---------------------------------------------------------------- small helpers

def esc(token):
    """RFC 6901 escaping of one JSON pointer token."""
    return str(token).replace("~", "~0").replace("/", "~1")


def P(*parts):
    return "/" + "/".join(esc(p) for p in parts)


def sha256_bytes(raw):
    return hashlib.sha256(raw).hexdigest()


def _no_dups(pairs):
    d = {}
    for k, v in pairs:
        if k in d:
            raise InfraError("duplicate key in JSON: %r" % k)
        d[k] = v
    return d


def _bad_const(name):
    raise InfraError("non-standard JSON constant: %s" % name)


def load_json(path, what):
    p = Path(path)
    try:
        raw = p.read_bytes()
    except OSError as e:
        raise InfraError("cannot read %s %s: %s" % (what, p, e))
    try:
        data = json.loads(raw.decode("utf-8-sig"), object_pairs_hook=_no_dups, parse_constant=_bad_const)
    except InfraError:
        raise
    except (UnicodeDecodeError, ValueError) as e:
        raise InfraError("invalid JSON in %s %s: %s" % (what, p, e))
    return data, sha256_bytes(raw)


_TS_RE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(\.\d{1,9})?(Z|[+-]\d{2}:\d{2})$")
_DATE_RE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})$")


def parse_ts(s):
    m = _TS_RE.match(s) if isinstance(s, str) else None
    if not m:
        return None
    try:
        y, mo, d, h, mi, se = (int(m.group(i)) for i in range(1, 7))
        micro = int(((m.group(7) or ".")[1:] + "000000")[:6])
        tz = m.group(8)
        if tz == "Z":
            offset = dt.timezone.utc
        else:
            sign = 1 if tz[0] == "+" else -1
            offset = dt.timezone(sign * dt.timedelta(hours=int(tz[1:3]), minutes=int(tz[4:6])))
        return dt.datetime(y, mo, d, h, mi, se, micro, tzinfo=offset)
    except ValueError:
        return None


def parse_date(s):
    m = _DATE_RE.match(s) if isinstance(s, str) else None
    if not m:
        return None
    try:
        return dt.date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
    except ValueError:
        return None


# ---------------------------------------------------------------- mini JSON Schema engine
# Supported keywords: $ref (local), type, const, enum, required, properties,
# additionalProperties (bool or schema), items, minItems, maxItems, uniqueItems,
# minimum, maximum, minLength, pattern, format (date-time, date).

def _jtype(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "boolean"
    if isinstance(v, int):
        return "integer"
    if isinstance(v, float):
        return "number"
    if isinstance(v, str):
        return "string"
    if isinstance(v, list):
        return "array"
    return "object"


def _is_type(v, t):
    if t == "object":
        return isinstance(v, dict)
    if t == "array":
        return isinstance(v, list)
    if t == "string":
        return isinstance(v, str)
    if t == "boolean":
        return isinstance(v, bool)
    if t == "null":
        return v is None
    if t == "number":
        return isinstance(v, (int, float)) and not isinstance(v, bool)
    if t == "integer":
        if isinstance(v, bool):
            return False
        return isinstance(v, int) or (isinstance(v, float) and v.is_integer())
    raise InfraError("schema: unsupported type keyword %r" % t)


def _same(a, b):
    return type(a) is type(b) and a == b


def _resolve_ref(root, ref):
    if not isinstance(ref, str) or not ref.startswith("#/"):
        raise InfraError("schema: unsupported $ref %r" % (ref,))
    node = root
    for part in ref[2:].split("/"):
        part = part.replace("~1", "/").replace("~0", "~")
        if not isinstance(node, dict) or part not in node:
            raise InfraError("schema: unresolved $ref %s" % ref)
        node = node[part]
    return node


_VALIDATION_KEYWORDS = frozenset([
    "$ref", "type", "const", "enum", "required", "properties", "additionalProperties", "items",
    "minItems", "maxItems", "uniqueItems", "minimum", "maximum", "minLength", "maxLength",
    "pattern", "format", "propertyNames",
])
_ANNOTATION_KEYWORDS = frozenset([
    "$schema", "$id", "$comment", "title", "description", "default", "examples", "$defs", "definitions",
])


def audit_schema(schema, path=""):
    """Fail closed on schema keywords this engine does not implement.

    Silently ignoring a validation keyword would turn a constraint into a pass."""
    if not isinstance(schema, dict):
        raise InfraError("schema: node at %s is not an object" % (path or "/"))
    for k in schema:
        if k not in _VALIDATION_KEYWORDS and k not in _ANNOTATION_KEYWORDS:
            raise InfraError("schema: unsupported keyword %r at %s" % (k, path or "/"))
    if "type" in schema and not isinstance(schema["type"], str):
        raise InfraError("schema: type at %s must be a single string" % (path or "/"))
    for k in ("properties", "$defs", "definitions"):
        sub = schema.get(k)
        if sub is None:
            continue
        if not isinstance(sub, dict):
            raise InfraError("schema: %s at %s must be an object" % (k, path or "/"))
        for name, child in sub.items():
            audit_schema(child, "%s/%s/%s" % (path, k, esc(name)))
    for k in ("items", "propertyNames"):
        if k in schema:
            audit_schema(schema[k], "%s/%s" % (path, k))
    if isinstance(schema.get("additionalProperties"), dict):
        audit_schema(schema["additionalProperties"], path + "/additionalProperties")


def check_schema(value, schema, root, ptr, errs):
    if not isinstance(schema, dict):
        raise InfraError("schema: node at %s is not an object" % (ptr or "/"))
    if "$ref" in schema:
        check_schema(value, _resolve_ref(root, schema["$ref"]), root, ptr, errs)
        return
    t = schema.get("type")
    if t is not None and not _is_type(value, t):
        errs.append((ptr, "expected %s, got %s" % (t, _jtype(value))))
        return
    if "const" in schema and not _same(value, schema["const"]):
        errs.append((ptr, "must be %s" % json.dumps(schema["const"])))
    if "enum" in schema and not any(_same(value, e) for e in schema["enum"]):
        errs.append((ptr, "must be one of %s" % json.dumps(schema["enum"])))
    if isinstance(value, bool):
        return
    if isinstance(value, (int, float)):
        if "minimum" in schema and value < schema["minimum"]:
            errs.append((ptr, "must be >= %s" % schema["minimum"]))
        if "maximum" in schema and value > schema["maximum"]:
            errs.append((ptr, "must be <= %s" % schema["maximum"]))
    elif isinstance(value, str):
        if "minLength" in schema and len(value) < schema["minLength"]:
            errs.append((ptr, "must not be shorter than %d characters" % schema["minLength"]))
        if "maxLength" in schema and len(value) > schema["maxLength"]:
            errs.append((ptr, "must not be longer than %d characters" % schema["maxLength"]))
        if "pattern" in schema and not re.search(schema["pattern"], value):
            errs.append((ptr, "does not match pattern %s" % schema["pattern"]))
        fmt = schema.get("format")
        if fmt == "date-time" and parse_ts(value) is None:
            errs.append((ptr, "not an RFC 3339 date-time"))
        elif fmt == "date" and parse_date(value) is None:
            errs.append((ptr, "not a YYYY-MM-DD date"))
    elif isinstance(value, list):
        if "minItems" in schema and len(value) < schema["minItems"]:
            errs.append((ptr, "needs at least %d item(s)" % schema["minItems"]))
        if "maxItems" in schema and len(value) > schema["maxItems"]:
            errs.append((ptr, "allows at most %d item(s)" % schema["maxItems"]))
        if schema.get("uniqueItems"):
            seen = set()
            for it in value:
                k = json.dumps(it, sort_keys=True)
                if k in seen:
                    errs.append((ptr, "items must be unique"))
                    break
                seen.add(k)
        if "items" in schema:
            for i, it in enumerate(value):
                check_schema(it, schema["items"], root, "%s/%d" % (ptr, i), errs)
    elif isinstance(value, dict):
        props = schema.get("properties", {})
        for req in schema.get("required", []):
            if req not in value:
                errs.append((ptr, "missing required property '%s'" % req))
        addl = schema.get("additionalProperties", True)
        if "propertyNames" in schema:
            for k in value:
                check_schema(k, schema["propertyNames"], root, "%s/%s" % (ptr, esc(k)), errs)
        for k, v in value.items():
            sub = "%s/%s" % (ptr, esc(k))
            if k in props:
                check_schema(v, props[k], root, sub, errs)
            elif addl is False:
                errs.append((sub, "unexpected property '%s'" % k))
            elif isinstance(addl, dict):
                check_schema(v, addl, root, sub, errs)


# ---------------------------------------------------------------- policy, findings

REQUIRED_LIMITS = (
    "tolerance_cm", "prediction_residual_factor", "min_lever_arm_m", "headroom_warn_ratio",
    "max_hold_ms", "warn_hold_ms", "max_flash_hz", "max_estop_response_ms", "coverage_warn_pct",
    "caption_min_angle_deg", "max_retention_days", "allowed_fps", "max_clip_ms", "min_loop_ms",
    "max_frame_pixels", "max_xr_media_bytes", "max_glb_triangles", "max_texture_px",
    "terms_evidence_window_days", "max_waiver_days", "min_waiver_reason_chars",
)


class Policy(object):
    def __init__(self, data):
        if not isinstance(data, dict):
            raise InfraError("policy root must be an object")
        self.version = data.get("policy_version")
        if not isinstance(self.version, str) or not re.match(r"^\d+\.\d+\.\d+$", self.version):
            raise InfraError("policy: policy_version must be MAJOR.MINOR.PATCH")
        lim = data.get("limits")
        if not isinstance(lim, dict):
            raise InfraError("policy: limits missing")
        missing = [k for k in REQUIRED_LIMITS if k not in lim]
        if missing:
            raise InfraError("policy: missing limits: %s" % ", ".join(missing))
        tol = lim["tolerance_cm"]
        if not isinstance(tol, dict) or any(
                not isinstance(tol.get(k), (int, float)) or tol.get(k) <= 0
                for k in ("precise", "body_adjacent", "loose")):
            raise InfraError("policy: tolerance_cm needs positive precise, body_adjacent, loose")
        self.L = lim
        self.waivable = data.get("waivable", {})
        if not isinstance(self.waivable, dict) or any(not isinstance(v, bool) for v in self.waivable.values()):
            raise InfraError("policy: waivable must map rule ids to booleans")
        self.severity_overrides = data.get("severity_overrides", {})
        if not isinstance(self.severity_overrides, dict):
            raise InfraError("policy: severity_overrides must be an object")
        for rid, sev in self.severity_overrides.items():
            if rid not in RULES or sev not in SEVERITIES:
                raise InfraError("policy: bad severity override %r: %r" % (rid, sev))
        self.legacy_severity = data.get("legacy_severity", {})
        if not isinstance(self.legacy_severity, dict):
            raise InfraError("policy: legacy_severity must be an object")
        for rid, sev in self.legacy_severity.items():
            if rid not in ("XR001", "PV001") or sev not in SEVERITIES:
                raise InfraError("policy: bad legacy_severity entry %r: %r" % (rid, sev))


class Finding(object):
    def __init__(self, rule, pointer, message, key, severity):
        self.rule = rule
        self.pointer = pointer
        self.message = message
        self.key = key
        self.severity = severity
        self.fp = hashlib.sha256(("%s|%s|%s" % (rule, pointer, key)).encode("utf-8")).hexdigest()[:16]
        self.waiver = None


class Out(object):
    def __init__(self, policy):
        self.policy = policy
        self.items = []

    def add(self, rule, pointer, message, key="", severity=None):
        if rule not in RULES:
            raise InfraError("internal: unknown rule %s" % rule)
        sev = self.policy.severity_overrides.get(rule) or severity or RULES[rule][1]
        self.items.append(Finding(rule, pointer, message, key, sev))


# ---------------------------------------------------------------- base pack accessors

def base_state_items(pack):
    """List of (pointer_token, state_dict) in pack order, or None if the structure is not recognized."""
    st = pack.get("states")
    if isinstance(st, list) and st:
        for s in st:
            if not (isinstance(s, dict) and isinstance(s.get("id"), str)):
                return None
        return [(i, s) for i, s in enumerate(st)]
    if isinstance(st, dict) and st:
        return [(k, dict(v, id=k) if isinstance(v, dict) else {"id": k}) for k, v in st.items()]
    return None


def base_state_ids(pack):
    items = base_state_items(pack)
    return None if items is None else [s["id"] for _, s in items]


def _asset_key(x):
    """The repository pack uses asset_id; id is accepted as a fallback."""
    for k in ("asset_id", "id"):
        if isinstance(x.get(k), str):
            return x[k]
    return None


def base_assets(pack):
    a = pack.get("assets")
    if isinstance(a, list):
        out = {}
        for x in a:
            key = _asset_key(x) if isinstance(x, dict) else None
            if key is None:
                return None
            out[key] = x
        return out
    if isinstance(a, dict):
        return dict((k, v) for k, v in a.items() if isinstance(v, dict))
    return None


def base_surfaces(pack):
    """target_surfaces as in the repository pack; surfaces is accepted as a fallback."""
    for key in ("target_surfaces", "surfaces"):
        s = pack.get(key)
        if isinstance(s, list):
            return [x for x in s if isinstance(x, str)]
        if isinstance(s, dict):
            return list(s.keys())
    return None


class Ctx(object):
    def __init__(self, pack, policy, now_date, state_ids, assets):
        self.pack = pack
        self.xr = pack.get("xr_layer")
        self.prov = pack.get("provenance")
        self.pol = policy
        self.L = policy.L
        self.now_end = dt.datetime(now_date.year, now_date.month, now_date.day, 23, 59, 59, tzinfo=dt.timezone.utc)
        self.state_ids = state_ids
        self.assets = assets
        self.state_items = base_state_items(pack)
        self.states = dict((s["id"], s) for _, s in self.state_items)


# ---------------------------------------------------------------- XR rules

T1_KINDS = frozenset(["image", "video_alpha"])
BILLBOARD_KINDS = frozenset(["video_alpha", "image", "image_sequence"])
# kind of the base asset manifest that may back each xr_layer.media kind
BASE_KINDS_FOR_MEDIA = {
    "video_alpha": ("xr_clip",),
    "image_sequence": ("xr_clip",),
    "image": ("image",),
    "glb": ("glb_bundle",),
}


def r_state_coverage(c, out):
    base = set(c.state_ids)
    got = set(c.xr["states"].keys())
    for sid in sorted(base - got):
        out.add("XR003", "/xr_layer/states", "state '%s' has no xr_layer entry" % sid, "missing:" + sid)
    for sid in sorted(got - base):
        out.add("XR003", P("xr_layer", "states", sid), "xr_layer describes unknown state '%s'" % sid, "unknown:" + sid)


def _asset_ref(c, out, pointer, asset_id, kinds, role):
    if asset_id not in c.assets:
        out.add("XR005", pointer, "%s '%s' is not in the pack asset manifest" % (role, asset_id), "noasset:" + asset_id)
        return
    m = c.xr["media"].get(asset_id)
    if m is None:
        out.add("XR005", pointer, "%s '%s' has no xr_layer.media descriptor" % (role, asset_id), "nomedia:" + asset_id)
        return
    if m["kind"] not in kinds:
        out.add("XR005", pointer, "%s '%s' has kind '%s', allowed: %s" % (
            role, asset_id, m["kind"], ", ".join(sorted(kinds))), "kind:" + asset_id)


def r_asset_refs(c, out):
    for mid in sorted(c.xr["media"]):
        if mid not in c.assets:
            out.add("XR005", P("xr_layer", "media", mid),
                    "media descriptor '%s' has no asset in the manifest" % mid, "orphan:" + mid)
        else:
            want = BASE_KINDS_FOR_MEDIA[c.xr["media"][mid]["kind"]]
            have = c.assets[mid].get("kind")
            if have is not None and have not in want:
                out.add("XR005", P("xr_layer", "media", mid),
                        "asset '%s' has manifest kind '%s', but media kind '%s' needs %s"
                        % (mid, have, c.xr["media"][mid]["kind"], " or ".join(want)), "basekind:" + mid)
    for sid, st in sorted(c.xr["states"].items()):
        tiers = st["tiers"]
        if "T1" in tiers:
            _asset_ref(c, out, P("xr_layer", "states", sid, "tiers", "T1", "asset"),
                       tiers["T1"]["asset"], T1_KINDS, "T1 asset")
        if "T2" in tiers:
            t2 = tiers["T2"]
            kinds = BILLBOARD_KINDS if t2["render"] == "billboard" else frozenset(["glb"])
            _asset_ref(c, out, P("xr_layer", "states", sid, "tiers", "T2", "asset"),
                       t2["asset"], kinds, "T2 asset")
            for va in t2.get("viseme_assets", []):
                _asset_ref(c, out, P("xr_layer", "states", sid, "tiers", "T2", "viseme_assets"),
                           va, frozenset(["image"]), "viseme asset")


def r_safe_state(c, out):
    ss = c.xr["safe_state"]
    if ss not in c.state_ids:
        out.add("XR006", "/xr_layer/safe_state", "safe_state '%s' is not a pack state" % ss, "unknown")
        return
    st = c.xr["states"].get(ss)
    if st is None:
        return  # XR003 reports the missing entry
    if st["motion"] != "any":
        out.add("XR006", P("xr_layer", "states", ss, "motion"),
                "safe_state must stay valid while the robot moves (motion: any)", "motion")
    for t in ("T1", "T2"):
        if t in st["tiers"]:
            out.add("XR006", P("xr_layer", "states", ss, "tiers", t),
                    "safe_state must be T0 only (static, no animation)", "tier:" + t)


def r_precise(c, out):
    modes = set(c.xr["registration"]["accepted_modes"])
    for sid, st in sorted(c.xr["states"].items()):
        t2 = st["tiers"].get("T2")
        if not t2 or t2["tolerance_class"] != "precise":
            continue
        base = P("xr_layer", "states", sid)
        if not (modes & {"marker", "hybrid"}):
            out.add("XR007", base + "/tiers/T2/tolerance_class",
                    "precise tolerance needs marker or hybrid registration in accepted_modes", "mode:" + sid)
        if st["motion"] != "stationary":
            out.add("XR007", base + "/motion",
                    "precise tolerance is only credible while the robot is stationary", "motion:" + sid)


def registration_error_cm(c, t2):
    """Upper-bound registration error for the declared envelope (spec 10.4)."""
    reg = c.xr["registration"]
    l_eff = reg["latency_budget_ms"]["pose_to_photon"] / 1000.0
    if reg["prediction"] == "constant_velocity":
        l_eff *= c.L["prediction_residual_factor"]
    off = t2["attach"]["offset_m"]
    lever = max(math.hypot(off[0], off[1]), c.L["min_lever_arm_m"])
    e_lin = reg["max_speed_mps"] * l_eff * 100.0
    e_ang = math.radians(reg["max_turn_rate_dps"]) * lever * l_eff * 100.0
    return math.hypot(e_lin, e_ang)


def r_budget(c, out):
    for sid, st in sorted(c.xr["states"].items()):
        t2 = st["tiers"].get("T2")
        if not t2 or st["motion"] != "any":
            continue
        tol = c.L["tolerance_cm"][t2["tolerance_class"]]
        e = registration_error_cm(c, t2)
        ptr = P("xr_layer", "states", sid, "tiers", "T2", "tolerance_class")
        if e > tol:
            out.add("XR008", ptr, "estimated registration error %.1f cm exceeds the %s tolerance of %s cm at the declared "
                    "speed, turn rate and latency; use a looser class or make the state stationary"
                    % (e, t2["tolerance_class"], tol), "over:" + sid)
        elif e > tol * c.L["headroom_warn_ratio"]:
            out.add("XR008", ptr, "estimated registration error %.1f cm leaves little headroom under the %s tolerance of %s cm"
                    % (e, t2["tolerance_class"], tol), "tight:" + sid, severity="warning")


def r_moving_fallback(c, out):
    states = c.xr["states"]
    for sid, st in sorted(states.items()):
        if st["motion"] != "stationary":
            continue
        ptr = P("xr_layer", "states", sid, "moving_fallback")
        fb = st.get("moving_fallback")
        if fb is None:
            out.add("XR009", P("xr_layer", "states", sid), "stationary state needs moving_fallback", "missing:" + sid)
        elif fb == sid:
            out.add("XR009", ptr, "moving_fallback must not point to the state itself", "self:" + sid)
        elif fb not in states:
            out.add("XR009", ptr, "moving_fallback '%s' is not a described state" % fb, "unknown:" + sid)
        elif states[fb]["motion"] != "any":
            out.add("XR009", ptr, "moving_fallback '%s' must itself be valid while moving (motion: any)" % fb, "notany:" + sid)


def r_loss_policy(c, out):
    lp = c.xr["registration"]["loss_policy"]
    if lp["hold_ms"] > c.L["max_hold_ms"]:
        out.add("XR010", "/xr_layer/registration/loss_policy/hold_ms",
                "hold_ms %d exceeds the limit %d: a frozen layer drifts away from the robot" % (lp["hold_ms"], c.L["max_hold_ms"]), "hold")
    elif lp["hold_ms"] > c.L["warn_hold_ms"]:
        out.add("XR010", "/xr_layer/registration/loss_policy/hold_ms",
                "hold_ms %d is above the advisory %d" % (lp["hold_ms"], c.L["warn_hold_ms"]), "holdwarn", severity="warning")


def r_safety(c, out):
    s = c.xr["safety"]
    if s["max_flash_hz"] > c.L["max_flash_hz"]:
        out.add("XR011", "/xr_layer/safety/max_flash_hz",
                "max_flash_hz %s exceeds %s (general flash threshold, 3 flashes per second)" % (s["max_flash_hz"], c.L["max_flash_hz"]), "flash")
    if s["estop_response_ms"] > c.L["max_estop_response_ms"]:
        out.add("XR011", "/xr_layer/safety/estop_response_ms",
                "estop_response_ms %d exceeds %d" % (s["estop_response_ms"], c.L["max_estop_response_ms"]), "estop")
    if s["max_fov_coverage_pct"] > c.L["coverage_warn_pct"]:
        out.add("XR023", "/xr_layer/safety/max_fov_coverage_pct",
                "coverage %s%% is above the heuristic %s%%" % (s["max_fov_coverage_pct"], c.L["coverage_warn_pct"]), "coverage")
    if s["min_caption_angle_deg"] < c.L["caption_min_angle_deg"]:
        out.add("XR014", "/xr_layer/safety/min_caption_angle_deg",
                "caption angle %s deg is below the guideline %s deg" % (s["min_caption_angle_deg"], c.L["caption_min_angle_deg"]), "caption")


def _extent_box(attach, bounds):
    off, mn, mx = attach["offset_m"], bounds["min"], bounds["max"]
    r = math.hypot(max(abs(mn[0]), abs(mx[0])), max(abs(mn[1]), abs(mx[1])))
    return ((off[0] - r, off[1] - r, off[2] + mn[2]), (off[0] + r, off[1] + r, off[2] + mx[2]))


def _overlap(a, b):
    return all(a[0][i] <= b[1][i] and b[0][i] <= a[1][i] for i in range(3))


def r_keep_out(c, out):
    vols = []
    for i, v in enumerate(c.xr["keep_out"]):
        if any(v["min"][k] >= v["max"][k] for k in range(3)):
            out.add("XR012", P("xr_layer", "keep_out", i), "keep_out volume '%s' has min >= max" % v["id"], "badvol:" + v["id"])
        else:
            vols.append(v)
    for sid, st in sorted(c.xr["states"].items()):
        t2 = st["tiers"].get("T2")
        if not t2:
            continue
        b = t2["bounds_m"]
        if any(b["min"][k] >= b["max"][k] for k in range(3)):
            out.add("XR012", P("xr_layer", "states", sid, "tiers", "T2", "bounds_m"), "bounds_m has min >= max", "badbounds:" + sid)
            continue
        box = _extent_box(t2["attach"], b)
        for v in vols:
            if v["frame"] == t2["attach"]["frame"] and _overlap(box, (tuple(v["min"]), tuple(v["max"]))):
                out.add("XR012", P("xr_layer", "states", sid, "tiers", "T2", "bounds_m"),
                        "character bounds overlap keep_out volume '%s' (frame %s)" % (v["id"], v["frame"]), "keepout:%s:%s" % (sid, v["id"]))


def r_disclosure(c, out):
    for loc, text in sorted(c.xr["disclosure"]["labels"].items()):
        if not text.strip():
            out.add("XR013", P("xr_layer", "disclosure", "labels", loc), "AI disclosure label '%s' is blank" % loc, "blank:" + loc)


def r_audit(c, out):
    if c.xr["audit"]["retention_days"] > c.L["max_retention_days"]:
        out.add("XR015", "/xr_layer/audit/retention_days",
                "retention_days %d is above the policy %d" % (c.xr["audit"]["retention_days"], c.L["max_retention_days"]), "retention")


def r_media(c, out):
    for mid, m in sorted(c.xr["media"].items()):
        ptr = P("xr_layer", "media", mid)
        if m["watermark_free"] is not True:
            out.add("XR020", ptr + "/watermark_free", "media '%s' carries a platform watermark" % mid, "watermark:" + mid)
        kind = m["kind"]
        if kind in ("video_alpha", "image_sequence"):
            for need in ("width", "height", "fps", "duration_ms"):
                if need not in m:
                    out.add("XR020", ptr, "%s '%s' needs '%s'" % (kind, mid, need), "need:%s:%s" % (need, mid))
            if "fps" in m and m["fps"] not in c.L["allowed_fps"]:
                out.add("XR020", ptr + "/fps", "fps %s is not in %s" % (m["fps"], c.L["allowed_fps"]), "fps:" + mid)
            if "duration_ms" in m and m["duration_ms"] > c.L["max_clip_ms"]:
                out.add("XR020", ptr + "/duration_ms", "duration %d ms exceeds %d" % (m["duration_ms"], c.L["max_clip_ms"]), "dur:" + mid)
            if "width" in m and "height" in m and m["width"] * m["height"] > c.L["max_frame_pixels"]:
                out.add("XR020", ptr, "frame %dx%d exceeds %d pixels" % (m["width"], m["height"], c.L["max_frame_pixels"]), "pixels:" + mid)
        if kind == "video_alpha":
            if m.get("has_audio") is not False:
                out.add("XR020", ptr + "/has_audio", "video_alpha '%s' must declare has_audio: false (audio comes from the robot TTS)" % mid, "audio:" + mid)
            am = m.get("alpha_mode")
            if am not in ("packed_lr", "packed_tb", "native_vp9"):
                out.add("XR020", ptr + "/alpha_mode", "video_alpha '%s' needs alpha_mode packed_lr, packed_tb or native_vp9" % mid, "alpha:" + mid)
            elif am == "packed_lr" and "width" in m and m["width"] % 2:
                out.add("XR020", ptr + "/width", "packed_lr needs an even encoded width", "evenw:" + mid)
            elif am == "packed_tb" and "height" in m and m["height"] % 2:
                out.add("XR020", ptr + "/height", "packed_tb needs an even encoded height", "evenh:" + mid)
            lp = m.get("loop")
            if lp is not None and "duration_ms" in m:
                if not (0 <= lp["in_ms"] < lp["out_ms"] <= m["duration_ms"]):
                    out.add("XR020", ptr + "/loop", "loop needs 0 <= in_ms < out_ms <= duration_ms", "loop:" + mid)
                elif lp["out_ms"] - lp["in_ms"] < c.L["min_loop_ms"]:
                    out.add("XR020", ptr + "/loop", "loop shorter than %d ms repeats visibly" % c.L["min_loop_ms"], "looplen:" + mid)
        if kind in ("image", "video_alpha", "image_sequence") and ("width" not in m or "height" not in m):
            out.add("XR020", ptr, "%s '%s' needs width and height" % (kind, mid), "size:" + mid)
        if kind == "glb":
            if "triangles" not in m or "texture_max_px" not in m:
                out.add("XR020", ptr, "glb '%s' needs triangles and texture_max_px" % mid, "glbneed:" + mid)
            else:
                if m["triangles"] > c.L["max_glb_triangles"]:
                    out.add("XR020", ptr + "/triangles", "%d triangles exceed %d" % (m["triangles"], c.L["max_glb_triangles"]), "tris:" + mid)
                if m["texture_max_px"] > c.L["max_texture_px"]:
                    out.add("XR020", ptr + "/texture_max_px", "texture %d px exceeds %d" % (m["texture_max_px"], c.L["max_texture_px"]), "tex:" + mid)


def r_budget_bytes(c, out):
    total = 0
    for mid in sorted(c.xr["media"]):
        a = c.assets.get(mid)
        if a is None:
            continue
        b = a.get("bytes")
        if not isinstance(b, int) or isinstance(b, bool):
            out.add("XR021", P("xr_layer", "media", mid), "asset '%s' has no integer bytes: the budget cannot be verified" % mid,
                    "nobytes:" + mid, severity="warning")
            continue
        if b == 0:
            out.add("XR021", P("xr_layer", "media", mid), "asset '%s' declares bytes: 0 (placeholder?)" % mid,
                    "zero:" + mid, severity="warning")
        total += b
    if total > c.L["max_xr_media_bytes"]:
        out.add("XR021", "/xr_layer/media", "XR media totals %d bytes, limit %d" % (total, c.L["max_xr_media_bytes"]), "total")


def r_visemes(c, out):
    for sid, st in sorted(c.xr["states"].items()):
        t2 = st["tiers"].get("T2")
        if not t2:
            continue
        va = t2.get("viseme_assets", [])
        ptr = P("xr_layer", "states", sid, "tiers", "T2", "speaking_driver")
        if t2["speaking_driver"] == "viseme_lite" and not (3 <= len(va) <= 5):
            out.add("XR022", ptr, "viseme_lite needs 3 to 5 viseme_assets, found %d" % len(va), "count:" + sid)
        if t2["speaking_driver"] != "viseme_lite" and va:
            out.add("XR022", ptr, "viseme_assets given but speaking_driver is '%s'" % t2["speaking_driver"], "extra:" + sid)


def r_device_tiers(c, out):
    dc = set(c.xr["device_classes"])
    can_t1 = bool(dc & {"display_ai_glasses", "wired_xr_glasses", "xr_headset"})
    can_t2 = bool(dc & {"wired_xr_glasses", "xr_headset"})
    for sid, st in sorted(c.xr["states"].items()):
        t = st["tiers"]
        if "T1" in t and not can_t1:
            out.add("XR024", P("xr_layer", "states", sid, "tiers", "T1"), "T1 declared, but no listed device class has a display", "t1:" + sid)
        if "T2" in t and not can_t2:
            out.add("XR024", P("xr_layer", "states", sid, "tiers", "T2"),
                    "T2 declared, but only display_ai_glasses (T2 only if the host confirms world anchoring) or audio classes are listed",
                    "t2:" + sid)


def r_voice_alignment(c, out):
    """line_id is '<state_id>#<index>', so the voice_lines arrays of one state must be index-aligned."""
    for token, st in c.state_items:
        vl = st.get("voice_lines")
        if not isinstance(vl, dict) or not vl:
            continue
        lengths = dict((loc, len(v)) for loc, v in vl.items() if isinstance(v, list))
        if len(set(lengths.values())) > 1:
            out.add("XR025", P("states", token, "voice_lines"),
                    "state '%s': voice_lines lengths differ across locales (%s); line_id '%s#<index>' needs "
                    "index-aligned arrays" % (st["id"], ", ".join("%s=%d" % kv for kv in sorted(lengths.items())), st["id"]),
                    "len:" + st["id"])


def r_glb_consistency(c, out):
    for sid, st in sorted(c.xr["states"].items()):
        t2 = st["tiers"].get("T2")
        if not t2 or t2["render"] != "glb":
            continue
        xr1 = c.states.get(sid, {}).get("xr")
        bundle = xr1.get("bundle_asset") if isinstance(xr1, dict) else None
        if bundle is not None and bundle != t2["asset"]:
            out.add("XR026", P("xr_layer", "states", sid, "tiers", "T2", "asset"),
                    "T2 glb asset '%s' differs from xr.bundle_asset '%s' of the v1 state" % (t2["asset"], bundle),
                    "glb:" + sid)


XR_RULES = (r_state_coverage, r_asset_refs, r_safe_state, r_precise, r_budget, r_moving_fallback,
            r_loss_policy, r_safety, r_keep_out, r_disclosure, r_audit, r_media, r_budget_bytes,
            r_visemes, r_device_tiers, r_voice_alignment, r_glb_consistency)


# ---------------------------------------------------------------- provenance rules

def r_pv_coverage(c, out):
    prov = c.prov
    jobs = prov["generation"]["jobs"]
    hand = set(prov.get("hand_made_assets", []))
    owner = {}
    for i, job in enumerate(jobs):
        for aid in job["produces_assets"]:
            owner.setdefault(aid, []).append(job["job_id"])
            if aid not in c.assets:
                out.add("PV002", P("provenance", "generation", "jobs", i, "produces_assets"),
                        "job '%s' lists asset '%s' that is not in the manifest" % (job["job_id"], aid), "ghost:" + aid)
    for aid, js in sorted(owner.items()):
        if len(js) > 1:
            out.add("PV002", "/provenance/generation/jobs", "asset '%s' is claimed by several jobs: %s" % (aid, ", ".join(js)), "multi:" + aid)
        if aid in hand:
            out.add("PV002", "/provenance/hand_made_assets", "asset '%s' is both generated and hand made" % aid, "both:" + aid)
    for i, pp in enumerate(prov.get("post_processing", [])):
        for aid in pp["asset_ids"]:
            if aid not in c.assets:
                out.add("PV002", P("provenance", "post_processing", i, "asset_ids"),
                        "post-processing step '%s' references unknown asset '%s'" % (pp["step"], aid), "ppghost:" + aid)
    if c.xr is not None:
        for mid in sorted(c.xr["media"]):
            if mid not in owner and mid not in hand:
                out.add("PV002", P("xr_layer", "media", mid),
                        "XR asset '%s' is covered by neither a generation job nor hand_made_assets" % mid, "uncovered:" + mid)


def r_pv_terms(c, out):
    prov = c.prov
    te = prov["terms_evidence"]
    base = "/provenance/terms_evidence"
    if te["commercial_use"] is not True:
        out.add("PV003", base + "/commercial_use", "terms evidence does not confirm commercial use of outputs", "commercial")
    if te["watermark_free"] is not True:
        out.add("PV003", base + "/watermark_free", "terms evidence: outputs were not watermark-free", "watermark")
    if te["plan_kind"] == "free":
        out.add("PV003", base + "/plan_kind", "free plan: outputs carry a watermark and weaker rights", "free")
    cap = parse_ts(te["captured_at"])
    window = dt.timedelta(days=c.L["terms_evidence_window_days"])
    for i, job in enumerate(prov["generation"]["jobs"]):
        gen = parse_ts(job["generated_at"])
        if abs(cap - gen) > window:
            out.add("PV003", P("provenance", "generation", "jobs", i, "generated_at"),
                    "terms were captured %d days away from generation of job '%s'; capture the terms at generation time"
                    % (abs((cap - gen).days), job["job_id"]), "window:" + job["job_id"], severity="warning")
    if te["training_exposure"] == "default_may_train":
        out.add("PV008", base + "/training_exposure",
                "on this plan prompts and reference images may be used to improve the platform models; "
                "confidential characters need an enterprise agreement", "train")


def r_pv_original(c, out):
    char = c.pack.get("character")
    if not (isinstance(char, dict) and char.get("original_design") is True):
        return
    ss = c.prov["similarity_screening"]
    hr = c.prov["human_review"]
    if ss["result"] == "fail":
        out.add("PV004", "/provenance/similarity_screening/result", "similarity screening failed: original_design: true cannot stand", "fail")
    elif ss["result"] == "manual_review" and hr["decision"] != "approved":
        out.add("PV004", "/provenance/similarity_screening/result", "screening asked for manual review and no approval is recorded", "manual")


def r_pv_review(c, out):
    hr = c.prov["human_review"]
    if hr["decision"] != "approved":
        out.add("PV005", "/provenance/human_review/decision", "human review decision is '%s'" % hr["decision"], "decision")


def r_pv_credentials(c, out):
    cc = c.prov["content_credentials"]
    required = "KZ" in (c.xr["jurisdictions"] if c.xr is not None else [])
    sev = "error" if required else "warning"
    if cc["machine_readable"] is not True or cc["method"] == "none":
        out.add("PV006", "/provenance/content_credentials",
                "no machine-readable AI marking%s" % (" (required for KZ)" if required else ""), "marking", severity=sev)


def r_pv_inputs(c, out):
    for i, job in enumerate(c.prov["generation"]["jobs"]):
        for j, ref in enumerate(job.get("reference_inputs", [])):
            ptr = P("provenance", "generation", "jobs", i, "reference_inputs", j)
            if ref["rights"] in ("third_party", "unknown"):
                out.add("PV007", ptr + "/rights", "reference input has rights '%s'" % ref["rights"], "rights:%s:%d" % (job["job_id"], j))
            elif ref["rights"] == "licensed" and "evidence_sha256" not in ref:
                out.add("PV007", ptr, "licensed reference input needs evidence_sha256", "evidence:%s:%d" % (job["job_id"], j))


def r_pv_time(c, out):
    prov = c.prov
    gens = [parse_ts(j["generated_at"]) for j in prov["generation"]["jobs"]]
    scr = parse_ts(prov["similarity_screening"]["screened_at"])
    rev = parse_ts(prov["human_review"]["reviewed_at"])
    cap = parse_ts(prov["terms_evidence"]["captured_at"])
    for name, t, ptr in [("screened_at", scr, "/provenance/similarity_screening/screened_at"),
                         ("reviewed_at", rev, "/provenance/human_review/reviewed_at"),
                         ("captured_at", cap, "/provenance/terms_evidence/captured_at")]:
        if t > c.now_end:
            out.add("PV009", ptr, "%s is in the future" % name, "future:" + name)
    for i, g in enumerate(gens):
        if g > c.now_end:
            out.add("PV009", P("provenance", "generation", "jobs", i, "generated_at"), "generated_at is in the future", "future:gen%d" % i)
    if gens and scr < max(gens):
        out.add("PV009", "/provenance/similarity_screening/screened_at", "screening precedes the last generation", "order:screen")
    if rev < scr:
        out.add("PV009", "/provenance/human_review/reviewed_at", "human review precedes similarity screening", "order:review")


def r_pv_platform(c, out):
    g = c.prov["generation"]
    if g["platform"] == "other" and not g.get("platform_name", "").strip():
        out.add("PV010", "/provenance/generation/platform_name", "platform 'other' needs platform_name", "name")


def r_pv_authorship(c, out):
    ha = c.prov.get("human_authorship")
    if ha is None or len(ha["statement"].strip()) < 20:
        out.add("PV011", "/provenance/human_authorship",
                "no substantive human authorship statement; works made solely by AI without creative human contribution "
                "may be unprotected (KZ AI law)", "authorship")


def r_pv_prompts(c, out):
    for i, job in enumerate(c.prov["generation"]["jobs"]):
        if "prompt_sha256" not in job:
            out.add("PV012", P("provenance", "generation", "jobs", i), "job '%s' has no prompt_sha256" % job["job_id"], "prompt:" + job["job_id"])


PV_RULES = (r_pv_coverage, r_pv_terms, r_pv_original, r_pv_review, r_pv_credentials,
            r_pv_inputs, r_pv_time, r_pv_platform, r_pv_authorship, r_pv_prompts)


# ---------------------------------------------------------------- orchestration

def run_rules(pack, schema, pol, now_date, out):
    xr = pack.get("xr_layer")
    prov = pack.get("provenance")
    surfaces = base_surfaces(pack)
    claims_xr = surfaces is not None and "xr_glasses" in surfaces
    char = pack.get("character") if isinstance(pack.get("character"), dict) else {}
    original = char.get("original_design") is True

    legacy = xr is None and prov is None  # a v1 pack that has not adopted A1 yet

    def transition(rule):
        return pol.legacy_severity.get(rule) if legacy else None

    note = " (legacy v1 pack: reported as %s during the transition)"
    if claims_xr and xr is None:
        out.add("XR001", "/xr_layer",
                "pack claims the xr_glasses surface but has no xr_layer" + (note % transition("XR001") if transition("XR001") else ""),
                "missing", severity=transition("XR001"))
    if (xr is not None or original or claims_xr) and prov is None:
        out.add("PV001", "/provenance",
                "provenance is required for packs with an XR layer or original_design: true"
                + (note % transition("PV001") if transition("PV001") else ""),
                "missing", severity=transition("PV001"))
    if legacy:
        return

    errs = []
    check_schema(pack, schema, schema, "", errs)
    for ptr, msg in errs:
        out.add("XR002", ptr or "/", msg, msg)
    if errs:
        return  # semantic rules need a well-formed structure

    state_ids = base_state_ids(pack)
    assets = base_assets(pack)
    if state_ids is None or assets is None:
        out.add("XR000", "/", "base pack structure not recognized: expected non-empty 'states' whose items have an 'id' and "
                "an 'assets' list whose items have an 'asset_id' (or 'id'); adapt the accessors if your schema differs", "structure")
        return
    c = Ctx(pack, pol, now_date, state_ids, assets)
    if xr is not None:
        for rule in XR_RULES:
            rule(c, out)
    if prov is not None:
        for rule in PV_RULES:
            rule(c, out)


def _load_waivers(path):
    data, _ = load_json(path, "waivers")
    if isinstance(data, dict):
        data = data.get("waivers")
    if not isinstance(data, list):
        raise InfraError("waivers file must be a list or an object with a 'waivers' list")
    return data


def apply_waivers(out, waivers, pack, pol, now_date):
    prov = pack.get("provenance") if isinstance(pack.get("provenance"), dict) else {}
    creator = prov.get("creator") if isinstance(prov.get("creator"), dict) else {}
    creator_org = creator.get("org_id")
    pack_version = pack.get("pack_version")
    snapshot = list(out.items)
    need = ("rule", "fingerprint", "pack_version", "reason", "approver", "approver_org", "expires")
    for i, w in enumerate(waivers):
        loc = "waivers#/%d" % i
        if not isinstance(w, dict):
            out.add("WV001", loc, "waiver %d is not an object" % i, "w%d:shape" % i)
            continue
        miss = [k for k in need if not isinstance(w.get(k), str) or not w.get(k).strip()]
        exp = parse_date(w.get("expires")) if isinstance(w.get("expires"), str) else None
        if miss or exp is None:
            out.add("WV001", loc, "waiver %d malformed (missing/blank: %s%s)" % (
                i, ", ".join(miss) or "none", "; expires must be YYYY-MM-DD" if exp is None else ""), "w%d:malformed" % i)
            continue
        targets = [f for f in snapshot if f.rule == w["rule"] and f.fp == w["fingerprint"]]
        if not targets:
            out.add("WV001", loc, "waiver %d for %s matches no current finding (stale waiver?)" % (i, w["rule"]), "w%d:nomatch" % i)
            continue
        why = []
        if w["pack_version"] != pack_version:
            why.append("pack_version %s != %s" % (w["pack_version"], pack_version))
        if exp < now_date:
            why.append("expired on %s" % w["expires"])
        elif (exp - now_date).days > pol.L["max_waiver_days"]:
            why.append("expires more than %d days ahead" % pol.L["max_waiver_days"])
        if len(w["reason"].strip()) < pol.L["min_waiver_reason_chars"]:
            why.append("reason shorter than %d characters" % pol.L["min_waiver_reason_chars"])
        if creator_org and w["approver_org"].strip() == creator_org:
            why.append("approver belongs to the creator organisation")
        if not pol.waivable.get(w["rule"], False):
            why.append("rule %s is not waivable" % w["rule"])
        if why:
            out.add("WV001", loc, "waiver %d for %s rejected: %s" % (i, w["rule"], "; ".join(why)), "w%d:rejected" % i)
        else:
            for f in targets:
                f.waiver = w


def exit_code(items):
    live = [f for f in items if f.waiver is None]
    if any(f.severity == "error" for f in live):
        return EXIT_ERROR
    if any(f.severity == "warning" for f in live):
        return EXIT_WARN
    return EXIT_CLEAN


class Report(object):
    def __init__(self):
        self.findings = []
        self.code = EXIT_INFRA
        self.pack_uri = ""
        self.digests = {}
        self.policy = None
        self.notes = []


def _rel(path):
    try:
        return os.path.relpath(str(path)).replace(os.sep, "/")
    except ValueError:
        return Path(path).name


def evaluate(pack_path, schema_path=DEFAULT_SCHEMA, policy_path=DEFAULT_POLICY, waivers_path=None, now_date=None):
    rep = Report()
    rep.pack_uri = _rel(pack_path)
    rep.digests["validator_sha256"] = sha256_bytes(Path(__file__).read_bytes())
    now_date = now_date or dt.date.today()
    schema, rep.digests["schema_sha256"] = load_json(schema_path, "schema")
    audit_schema(schema)
    pol_data, rep.digests["policy_sha256"] = load_json(policy_path, "policy")
    pol = Policy(pol_data)
    rep.policy = pol
    rep.digests["policy_version"] = pol.version
    pack, rep.digests["input_sha256"] = load_json(pack_path, "pack")
    if not isinstance(pack, dict):
        raise InfraError("pack root must be a JSON object")
    waivers = _load_waivers(waivers_path) if waivers_path else []
    out = Out(pol)
    run_rules(pack, schema, pol, now_date, out)
    if waivers:
        apply_waivers(out, waivers, pack, pol, now_date)
    rep.findings = sorted(out.items, key=lambda f: (f.rule, f.pointer, f.fp))
    rep.code = exit_code(rep.findings)
    return rep


# ---------------------------------------------------------------- output

def render_text(rep):
    lines = ["%s %s, policy %s" % (TOOL_NAME, TOOL_VERSION, rep.digests.get("policy_version", "?")),
             "pack: %s (sha256 %s)" % (rep.pack_uri, rep.digests.get("input_sha256", "?")[:16])]
    errors = warnings = waived = 0
    for f in rep.findings:
        if f.waiver is not None:
            tag, waived = "WAIVED ", waived + 1
        elif f.severity == "error":
            tag, errors = "ERROR  ", errors + 1
        elif f.severity == "warning":
            tag, warnings = "WARN   ", warnings + 1
        else:
            tag = "NOTE   "
        lines.append("%s %s %s  %s  [fp=%s]" % (tag, f.rule, f.pointer, f.message, f.fp))
    lines.append("Summary: %d error(s), %d warning(s), %d waived" % (errors, warnings, waived))
    lines.append("exit %d" % rep.code)
    return "\n".join(lines)


def _lvl(sev):
    return {"error": "error", "warning": "warning"}.get(sev, "note")


def to_sarif(rep, infra_message=None):
    pol = rep.policy
    rules = []
    for rid in sorted(RULES):
        title, sev = RULES[rid]
        rules.append({
            "id": rid, "name": rid, "shortDescription": {"text": title},
            "defaultConfiguration": {"level": _lvl(sev)},
            "properties": {"waivable": bool(pol.waivable.get(rid, False)) if pol else False},
        })
    results = []
    for f in rep.findings:
        r = {
            "ruleId": f.rule, "level": _lvl(f.severity), "message": {"text": f.message},
            "locations": [{"physicalLocation": {"artifactLocation": {"uri": rep.pack_uri}},
                           "logicalLocations": [{"fullyQualifiedName": f.pointer, "kind": "member"}]}],
            "partialFingerprints": {"charpack/v1": f.fp},
        }
        if f.waiver is not None:
            r["suppressions"] = [{
                "kind": "external", "status": "accepted", "justification": f.waiver["reason"],
                "properties": {"approver": f.waiver["approver"], "approver_org": f.waiver["approver_org"],
                               "expires": f.waiver["expires"]},
            }]
        results.append(r)
    notifications = []
    if infra_message:
        notifications.append({"level": "error", "message": {"text": infra_message}})
    props = dict(rep.digests)
    props["tool_version"] = TOOL_VERSION
    return {
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {"driver": {"name": TOOL_NAME, "version": TOOL_VERSION, "rules": rules}},
            "artifacts": [{"location": {"uri": rep.pack_uri},
                           "hashes": ({"sha-256": rep.digests["input_sha256"]} if "input_sha256" in rep.digests else {})}],
            "results": results,
            "invocations": [{"executionSuccessful": rep.code != EXIT_INFRA, "exitCode": rep.code,
                             "toolExecutionNotifications": notifications}],
            "properties": props,
        }],
    }


def write_sarif(path, sarif):
    try:
        Path(path).write_text(json.dumps(sarif, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")
    except OSError as e:
        raise InfraError("cannot write SARIF %s: %s" % (path, e))


def list_rules(policy_path):
    pol = None
    try:
        pol = Policy(load_json(policy_path, "policy")[0])
    except InfraError:
        pass
    print("%-6s %-8s %-10s %s" % ("rule", "severity", "waivable", "title"))
    for rid in sorted(RULES):
        title, sev = RULES[rid]
        w = "?" if pol is None else ("yes" if pol.waivable.get(rid, False) else "no")
        print("%-6s %-8s %-10s %s" % (rid, sev, w, title))


def main(argv=None):
    ap = argparse.ArgumentParser(description="Gate for the XR layer (addendum A1) and provenance of a Character Pack.")
    ap.add_argument("pack", nargs="?", help="path to the pack JSON")
    ap.add_argument("--schema", default=str(DEFAULT_SCHEMA))
    ap.add_argument("--policy", default=str(DEFAULT_POLICY))
    ap.add_argument("--waivers", help="JSON file with waivers")
    ap.add_argument("--sarif", help="write SARIF 2.1.0 to this path")
    ap.add_argument("--now", help="evaluation date YYYY-MM-DD (default: today); used for waiver expiry and future timestamps")
    ap.add_argument("--list-rules", action="store_true")
    args = ap.parse_args(argv)

    if args.list_rules:
        list_rules(args.policy)
        return EXIT_CLEAN
    if not args.pack:
        ap.error("pack is required")

    rep = Report()
    rep.pack_uri = _rel(args.pack)
    try:
        now = parse_date(args.now) if args.now else None
        if args.now and now is None:
            raise InfraError("--now must be YYYY-MM-DD")
        rep = evaluate(args.pack, args.schema, args.policy, args.waivers, now)
        if args.sarif:
            write_sarif(args.sarif, to_sarif(rep))
        print(render_text(rep))
        return rep.code
    except InfraError as e:
        msg = "INFRASTRUCTURE FAILURE: %s" % e
    except Exception as e:  # a bug is an infrastructure failure, never a pass
        msg = "INFRASTRUCTURE FAILURE: unexpected %s: %s" % (type(e).__name__, e)
    print(msg, file=sys.stderr)
    rep.code = EXIT_INFRA
    if args.sarif:
        try:
            write_sarif(args.sarif, to_sarif(rep, infra_message=msg))
        except InfraError as e2:
            print(str(e2), file=sys.stderr)
    return EXIT_INFRA


if __name__ == "__main__":
    sys.exit(main())
